name: Deploy
concurrency: ${{ github.ref_name }}

on:
    push:
      branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.x.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Publish
      run: dotnet publish -c Release --no-build --output ./publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: publish
        path: ./publish
